Current branch
NataliiaIgra/PY200-DoubleLinkedList pull request #3
Opened 2021-03-02 15:13 UTC by NataliiaIgra

Доделала класс DoubleNode с использованием слабых ссылок. И сделала метод append в классе DoubleLinkedList. Но есть неуверенность по поводу того, что сделала. Можете глянуть?

2021-03-03 18:46 UTC, EnotYoyo requested changes
Идея была в том, чтобы не менять поведение базового LinkedList'а, а отнаследоваться от него :)

2021-03-03 18:46 UTC, EnotYoyo commented on double_linked_list.py
> +        return self._prev_node()
А есть там будет None?

2021-03-03 18:59 UTC, NataliiaIgra commented
> Идея была в том, чтобы не менять поведение базового LinkedList'а, а отнаследоваться от него :)

Я понимаю, что идея была отнаследоваться от LinkedList'а. Но я просто попыталась что-то еще добавить в его поведение (например, хранение хвоста для последующей работы с отрицательными индексами) или убрать повторяющийся код. Пока что я просто уточнить хотела по поводу слабых ссылок. А так еще ничего не готово.

2021-03-05 18:21 UTC, EnotYoyo approved these changes
Посмотрите на граничные условия, мне кажется, что там будут ошибки

2021-03-05 18:21 UTC, EnotYoyo commented on double_linked_list.py
> +        if index == len(self) - 1:
Вроде этот код будет работать неправильно, если длина списка будет 1 и попытаться вставить по индексу 0.

2021-03-05 18:21 UTC, EnotYoyo commented on double_linked_list.py
> +            self.head = self.head.next_node
а что если длина была 1? То tail тоже нужно сбросить.

2021-03-05 18:21 UTC, EnotYoyo commented on linked_list.py
> +    def is_iterable(self):
не понял смысл этого метода.)

2021-03-07 19:31 UTC, EnotYoyo approved these changes
Принято

2021-03-07 19:34 UTC, merged